# Generated by Django 4.1 on 2022-08-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="market_cap",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="coin",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
